---
- name: Check Ansible version
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Verify Ansible won't mess with you
      assert:
        that: "ansible_version.full is version_compare('2.17', '<')"
        msg: >
          "You must downgrade Ansible to 2.16 or it won't be able to work with most of old containers."


- name: Print os facts
  hosts: all
  tasks:
    - name: Print OS
      debug:
        msg: "{{ ansible_distribution }}"
    - name: Print fact
      debug:
        msg: "{{ some_fact }}"