apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-watcher
subjects:
- kind: User
  name: watcher
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-watcher
  apiGroup: rbac.authorization.k8s.io