apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-nginx
  labels:
    app: mt-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-nginx
  template:
    metadata:
      labels:
        app: mt-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
      - name: multitool
        image: praqma/network-multitool
        envFrom:
        - configMapRef:
            name: ports
      volumes:
      - name: index
        configMap:
          name: files