{
 "title": "Netology",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "CPU utilization, %"
    }
   ]
  },
  {
   "title": "CPU utilization, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=\"51.250.84.15:9100\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_load1{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "Load average (1m)"
    },
    {
     "expr": "node_load5{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "Load average (5m)"
    },
    {
     "expr": "node_load15{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "Load average (15m)"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RAM free, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"51.250.84.15:9100\"} / node_memory_MemTotal_bytes{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Disk free, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"51.250.84.15:9100\"}/node_filesystem_size_bytes{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk free space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"51.250.84.15:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}