---
  - name: Add Workers to the Swarm
    become: true
    shell: "docker swarm join --token {{ hostvars['master_node']['worker_token']['stdout'] }} {{ hostvars[inventory_hostname]['master_ip'] }}"
    ignore_errors: True