apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-nginx-deployment
  labels:
    app: init-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-nginx
  template:
    metadata:
      labels:
        app: init-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      initContainers:
      - name: nginx-check
        image: busybox
        command: ['sh', '-c', "until nslookup init-nginx-svc.default.svc.cluster.local; do echo waiting for init-nginx-svc; sleep 2; done; exit"]
    
    