apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.podLabels | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        {{- toYaml .Values.ingressPodSelector | nindent 8 }}