---
- name: "Create group {{ prometheus_group }}"
  become: true
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present

- name: "Add user {{ prometheus_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Get Prometheus archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus archive
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Make sure Prometheus dir exists
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Copy files to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item.src }}"
    dest: "{{ item.dest }}/{{ item.src }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  loop:
    - src: prometheus
      dest: /usr/local/bin
      mode: '0755'
    - src: promtool
      dest: /usr/local/bin
      mode: '0755'
    - src: prometheus.yml
      dest: /etc/prometheus
      mode: '0644'
  notify:
    - Restart and enable Prometheus service

- name: Copy directories to /etc/prometheus
  become: true
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
    dest: "/etc/prometheus/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    directory_mode: yes
    remote_src: yes
  loop:
    - console_libraries
    - consoles
  notify:
    - Restart and enable Prometheus service

- name: Add exporters to prometheus.yml
  become: true
  ansible.builtin.lineinfile:
    path: /etc/prometheus/prometheus.yml
    search_string: '      - targets: ["localhost:9090"]'
    line: '      - targets: ["localhost:9090", "{{ hostvars["node-exporter"]["ansible_host"] }}:9100"]'
  notify:
    - Restart and enable Prometheus service

- name: Add prometheus.service file
  become: true
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - Restart and enable Prometheus service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Check 9090 port
  ansible.builtin.wait_for:
    port: "9090"
    delay: 10