filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "docker_message"
      process_array: true
      max_depth: 2
      overwrite_keys: true
      add_error_key: true
      expand_keys: true

output.logstash:
  hosts: ["logstash:5044"]