apiVersion: v1
kind: ConfigMap
metadata:
  name: files
data:
  index.html: |
    <h1>Lorem ipsum dolor sit amet</h1>
    <p>consectetur adipiscing elit. Nam auctor sollicitudin mi, non interdum diam accumsan non. Proin sit amet auctor elit. Donec placerat dictum libero eget feugiat. Curabitur venenatis nibh ultricies, accumsan neque at, dapibus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam eget faucibus sapien. Etiam sed lorem semper, rhoncus lacus vel, ultricies sapien. Integer vitae malesuada nisi, in ultricies dui. In hendrerit placerat nibh gravida volutpat. Fusce convallis orci eget fermentum efficitur. Praesent tortor elit, vehicula lacinia iaculis nec, elementum quis velit. Ut egestas lectus vel magna consequat pharetra. Suspendisse mollis, quam vel sagittis interdum, nunc odio hendrerit mi, vitae consequat dui eros id mauris. Ut tristique efficitur sapien vel tempus. </p>