---
- name: Add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository into sources list
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install docker packages
  become: true
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable docker service
  become: true
  service:
    name: docker
    enabled: true