---
all:
  hosts:
    nexus-01:
      ansible_host: 178.154.203.75
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ansibler
    
    