all:
  hosts:
    node1:
      ansible_host: 192.168.0.21
      ip: 192.168.0.21
      access_ip: 192.168.0.21
    node2:
      ansible_host: 192.168.0.28
      ip: 192.168.0.28
      access_ip: 192.168.0.28
    node3:
      ansible_host: 192.168.0.15
      ip: 192.168.0.15
      access_ip: 192.168.0.15
    node4:
      ansible_host: 192.168.0.19
      ip: 192.168.0.19
      access_ip: 192.168.0.19
    node5:
      ansible_host: 192.168.0.12
      ip: 192.168.0.12
      access_ip: 192.168.0.12
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
