apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: backend
        image: praqma/network-multitool
